=== hms-dbmi/ppm-data/picnichealth/conditionReadable.schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "array",
  "title": "The Root Schema",
  "items": {
    "$id": "#/items",
    "type": "object",
    "title": "The Items Schema",
    "required": [
      "conditionId",
      "personId",
      "visitId",
      "conceptName",
      "additionalStandardConceptNames",
      "startDate",
      "startDatePrecision",
      "endDate",
      "endDatePrecision",
      "typeConceptName",
      "sourceConceptName"
    ],
    "properties": {
      "conditionId": {
        "$id": "#/items/properties/conditionId",
        "type": "string",
        "title": "The Conditionid Schema",
        "default": "",
        "examples": [
          "7df9675e-d490-4cf8-835d-e891cddeaaf5"
        ],
        "pattern": "^(.*)$"
      },
      "personId": {
        "$id": "#/items/properties/personId",
        "type": "string",
        "title": "The Personid Schema",
        "default": "",
        "examples": [
          "81163710-c2a2-4750-8e7f-8c7e18575695"
        ],
        "pattern": "^(.*)$"
      },
      "visitId": {
        "$id": "#/items/properties/visitId",
        "type": "string",
        "title": "The Visitid Schema",
        "default": "",
        "examples": [
          "9dd3d353-ae7d-4008-975c-c0bab77c36fe"
        ],
        "pattern": "^(.*)$"
      },
      "conceptName": {
        "$id": "#/items/properties/conceptName",
        "type": "string",
        "title": "The Conceptname Schema",
        "default": "",
        "examples": [
          "Malignant melanoma of skin of face"
        ],
        "pattern": "^(.*)$"
      },
      "additionalStandardConceptNames": {
        "$id": "#/items/properties/additionalStandardConceptNames",
        "type": "string",
        "title": "The Additionalstandardconceptnames Schema",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      },
      "startDate": {
        "$id": "#/items/properties/startDate",
        "type": "string",
        "title": "The Startdate Schema",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      },
      "startDatePrecision": {
        "$id": "#/items/properties/startDatePrecision",
        "type": "string",
        "title": "The Startdateprecision Schema",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      },
      "endDate": {
        "$id": "#/items/properties/endDate",
        "type": "string",
        "title": "The Enddate Schema",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      },
      "endDatePrecision": {
        "$id": "#/items/properties/endDatePrecision",
        "type": "string",
        "title": "The Enddateprecision Schema",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      },
      "typeConceptName": {
        "$id": "#/items/properties/typeConceptName",
        "type": "string",
        "title": "The Typeconceptname Schema",
        "default": "",
        "examples": [
          "Primary Condition"
        ],
        "pattern": "^(.*)$"
      },
      "sourceConceptName": {
        "$id": "#/items/properties/sourceConceptName",
        "type": "string",
        "title": "The Sourceconceptname Schema",
        "default": "",
        "examples": [
          "Malignant melanoma of skin of other and unspecified parts of face"
        ],
        "pattern": "^(.*)$"
      }
    }
  }
}

=== hms-dbmi/ppm-data/picnichealth/example/conditionReadable.json
[
  {
    "conditionId": "7df9675e-d490-4cf8-835d-e891cddeaaf5",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "visitId": "9dd3d353-ae7d-4008-975c-c0bab77c36fe",
    "conceptName": "Malignant melanoma of skin of face",
    "additionalStandardConceptNames": "",
    "startDate": "",
    "startDatePrecision": "",
    "endDate": "",
    "endDatePrecision": "",
    "typeConceptName": "Primary Condition",
    "sourceConceptName": "Malignant melanoma of skin of other and unspecified parts of face"
  },
  {
    "conditionId": "4d6ec14c-2f3a-4981-9c80-30c0befbc1db",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "visitId": "c39fbe44-d686-4d3d-8227-5d420fee3c02",
    "conceptName": "Malignant melanoma of skin",
    "additionalStandardConceptNames": "",
    "startDate": "",
    "startDatePrecision": "",
    "endDate": "",
    "endDatePrecision": "",
    "typeConceptName": "Primary Condition",
    "sourceConceptName": "Melanoma of skin, site unspecified"
  },
  {
    "conditionId": "f21d4cc5-ea85-45b5-aab6-bc0d7ac15452",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "visitId": "c39fbe44-d686-4d3d-8227-5d420fee3c02",
    "conceptName": "Jaw pain",
    "additionalStandardConceptNames": "",
    "startDate": "",
    "startDatePrecision": "",
    "endDate": "",
    "endDatePrecision": "",
    "typeConceptName": "Primary Condition",
    "sourceConceptName": "Jaw pain"
  },
  {
    "conditionId": "c85d79b8-ac29-4102-96f8-debc34a01db2",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "visitId": "c39fbe44-d686-4d3d-8227-5d420fee3c02",
    "conceptName": "Jaw pain",
    "additionalStandardConceptNames": "",
    "startDate": "",
    "startDatePrecision": "",
    "endDate": "",
    "endDatePrecision": "",
    "typeConceptName": "EHR problem list entry",
    "sourceConceptName": "Jaw pain"
  },
  {
    "conditionId": "ec4f5278-0fc2-4c5e-b269-d58af84189c8",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "visitId": "c39fbe44-d686-4d3d-8227-5d420fee3c02",
    "conceptName": "Malignant melanoma of skin",
    "additionalStandardConceptNames": "",
    "startDate": "",
    "startDatePrecision": "",
    "endDate": "",
    "endDatePrecision": "",
    "typeConceptName": "EHR problem list entry",
    "sourceConceptName": "Melanoma of skin, site unspecified"
  },
  {
    "conditionId": "b370f5b7-79cb-47ae-8ffd-c97a29be7d48",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "visitId": "aea5f6d1-5502-40e4-ad84-f67df1167f2d",
    "conceptName": "Malignant melanoma of skin",
    "additionalStandardConceptNames": "",
    "startDate": "",
    "startDatePrecision": "",
    "endDate": "",
    "endDatePrecision": "",
    "typeConceptName": "Primary Condition",
    "sourceConceptName": "Malignant melanoma of skin"
  },
  {
    "conditionId": "5cb05e1e-497a-4cf8-a257-d7959a9fb96a",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "visitId": "1c30423e-5389-4586-9806-9f175141f1a4",
    "conceptName": "Malignant melanoma of skin",
    "additionalStandardConceptNames": "",
    "startDate": "",
    "startDatePrecision": "",
    "endDate": "",
    "endDatePrecision": "",
    "typeConceptName": "Primary Condition",
    "sourceConceptName": "Melanoma of skin, site unspecified"
  },
  {
    "conditionId": "ca8bf817-6c6b-4b87-972c-bb6e63d2cae0",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "visitId": "ee2b3be2-9e51-44b2-a701-18bcbfaeff0b",
    "conceptName": "Malignant melanoma of skin",
    "additionalStandardConceptNames": "",
    "startDate": "",
    "startDatePrecision": "",
    "endDate": "",
    "endDatePrecision": "",
    "typeConceptName": "Primary Condition",
    "sourceConceptName": "Melanoma of skin, site unspecified"
  }
]
