=== hms-dbmi/ppm-data/picnichealth/condition.schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "array",
  "title": "The Root Schema",
  "items": {
    "$id": "#/items",
    "type": "object",
    "title": "The Items Schema",
    "required": [
      "conditionId",
      "personId",
      "visitId",
      "conceptId",
      "additionalStandardConceptIds",
      "startDate",
      "startDatePrecision",
      "endDate",
      "endDatePrecision",
      "typeConceptId",
      "sourceConceptId"
    ],
    "properties": {
      "conditionId": {
        "$id": "#/items/properties/conditionId",
        "type": "string",
        "title": "The Conditionid Schema",
        "default": "",
        "examples": [
          "7df9675e-d490-4cf8-835d-e891cddeaaf5"
        ],
        "pattern": "^(.*)$"
      },
      "personId": {
        "$id": "#/items/properties/personId",
        "type": "string",
        "title": "The Personid Schema",
        "default": "",
        "examples": [
          "81163710-c2a2-4750-8e7f-8c7e18575695"
        ],
        "pattern": "^(.*)$"
      },
      "visitId": {
        "$id": "#/items/properties/visitId",
        "type": "string",
        "title": "The Visitid Schema",
        "default": "",
        "examples": [
          "9dd3d353-ae7d-4008-975c-c0bab77c36fe"
        ],
        "pattern": "^(.*)$"
      },
      "conceptId": {
        "$id": "#/items/properties/conceptId",
        "type": "string",
        "title": "The Conceptid Schema",
        "default": "",
        "examples": [
          "d9aa4199-a705-5166-9b67-c4f2ece1ccef"
        ],
        "pattern": "^(.*)$"
      },
      "additionalStandardConceptIds": {
        "$id": "#/items/properties/additionalStandardConceptIds",
        "type": "string",
        "title": "The Additionalstandardconceptids Schema",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      },
      "startDate": {
        "$id": "#/items/properties/startDate",
        "type": "string",
        "title": "The Startdate Schema",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      },
      "startDatePrecision": {
        "$id": "#/items/properties/startDatePrecision",
        "type": "string",
        "title": "The Startdateprecision Schema",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      },
      "endDate": {
        "$id": "#/items/properties/endDate",
        "type": "string",
        "title": "The Enddate Schema",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      },
      "endDatePrecision": {
        "$id": "#/items/properties/endDatePrecision",
        "type": "string",
        "title": "The Enddateprecision Schema",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      },
      "typeConceptId": {
        "$id": "#/items/properties/typeConceptId",
        "type": "string",
        "title": "The Typeconceptid Schema",
        "default": "",
        "examples": [
          "f67d8cbc-98f8-5c90-9b03-155832f0d5cf"
        ],
        "pattern": "^(.*)$"
      },
      "sourceConceptId": {
        "$id": "#/items/properties/sourceConceptId",
        "type": "string",
        "title": "The Sourceconceptid Schema",
        "default": "",
        "examples": [
          "612b17bf-b1fe-5657-81aa-da16052978e6"
        ],
        "pattern": "^(.*)$"
      }
    }
  }
}

=== hms-dbmi/ppm-data/picnichealth/example/condition.json
[
  {
    "conditionId": "7df9675e-d490-4cf8-835d-e891cddeaaf5",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "visitId": "9dd3d353-ae7d-4008-975c-c0bab77c36fe",
    "conceptId": "d9aa4199-a705-5166-9b67-c4f2ece1ccef",
    "additionalStandardConceptIds": "",
    "startDate": "",
    "startDatePrecision": "",
    "endDate": "",
    "endDatePrecision": "",
    "typeConceptId": "f67d8cbc-98f8-5c90-9b03-155832f0d5cf",
    "sourceConceptId": "612b17bf-b1fe-5657-81aa-da16052978e6"
  },
  {
    "conditionId": "4d6ec14c-2f3a-4981-9c80-30c0befbc1db",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "visitId": "c39fbe44-d686-4d3d-8227-5d420fee3c02",
    "conceptId": "16cd021a-3828-59a9-b760-1f60c50b1cdf",
    "additionalStandardConceptIds": "",
    "startDate": "",
    "startDatePrecision": "",
    "endDate": "",
    "endDatePrecision": "",
    "typeConceptId": "f67d8cbc-98f8-5c90-9b03-155832f0d5cf",
    "sourceConceptId": "c643f23f-80fc-5886-ad51-4145ac88b802"
  },
  {
    "conditionId": "f21d4cc5-ea85-45b5-aab6-bc0d7ac15452",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "visitId": "c39fbe44-d686-4d3d-8227-5d420fee3c02",
    "conceptId": "1c67fed1-2f0a-5d79-969b-c40969df9cc2",
    "additionalStandardConceptIds": "",
    "startDate": "",
    "startDatePrecision": "",
    "endDate": "",
    "endDatePrecision": "",
    "typeConceptId": "f67d8cbc-98f8-5c90-9b03-155832f0d5cf",
    "sourceConceptId": "62a6439c-0089-518f-a17d-e1119475f1ac"
  },
  {
    "conditionId": "c85d79b8-ac29-4102-96f8-debc34a01db2",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "visitId": "c39fbe44-d686-4d3d-8227-5d420fee3c02",
    "conceptId": "1c67fed1-2f0a-5d79-969b-c40969df9cc2",
    "additionalStandardConceptIds": "",
    "startDate": "",
    "startDatePrecision": "",
    "endDate": "",
    "endDatePrecision": "",
    "typeConceptId": "5d3d2b6f-9a87-5d4d-addb-dd77e3886c91",
    "sourceConceptId": "62a6439c-0089-518f-a17d-e1119475f1ac"
  },
  {
    "conditionId": "ec4f5278-0fc2-4c5e-b269-d58af84189c8",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "visitId": "c39fbe44-d686-4d3d-8227-5d420fee3c02",
    "conceptId": "16cd021a-3828-59a9-b760-1f60c50b1cdf",
    "additionalStandardConceptIds": "",
    "startDate": "",
    "startDatePrecision": "",
    "endDate": "",
    "endDatePrecision": "",
    "typeConceptId": "5d3d2b6f-9a87-5d4d-addb-dd77e3886c91",
    "sourceConceptId": "c643f23f-80fc-5886-ad51-4145ac88b802"
  },
  {
    "conditionId": "b370f5b7-79cb-47ae-8ffd-c97a29be7d48",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "visitId": "aea5f6d1-5502-40e4-ad84-f67df1167f2d",
    "conceptId": "16cd021a-3828-59a9-b760-1f60c50b1cdf",
    "additionalStandardConceptIds": "",
    "startDate": "",
    "startDatePrecision": "",
    "endDate": "",
    "endDatePrecision": "",
    "typeConceptId": "f67d8cbc-98f8-5c90-9b03-155832f0d5cf",
    "sourceConceptId": "76923262-8805-5ef5-8cdf-4ea1a48dc366"
  },
  {
    "conditionId": "5cb05e1e-497a-4cf8-a257-d7959a9fb96a",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "visitId": "1c30423e-5389-4586-9806-9f175141f1a4",
    "conceptId": "16cd021a-3828-59a9-b760-1f60c50b1cdf",
    "additionalStandardConceptIds": "",
    "startDate": "",
    "startDatePrecision": "",
    "endDate": "",
    "endDatePrecision": "",
    "typeConceptId": "f67d8cbc-98f8-5c90-9b03-155832f0d5cf",
    "sourceConceptId": "c643f23f-80fc-5886-ad51-4145ac88b802"
  },
  {
    "conditionId": "ca8bf817-6c6b-4b87-972c-bb6e63d2cae0",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "visitId": "ee2b3be2-9e51-44b2-a701-18bcbfaeff0b",
    "conceptId": "16cd021a-3828-59a9-b760-1f60c50b1cdf",
    "additionalStandardConceptIds": "",
    "startDate": "",
    "startDatePrecision": "",
    "endDate": "",
    "endDatePrecision": "",
    "typeConceptId": "f67d8cbc-98f8-5c90-9b03-155832f0d5cf",
    "sourceConceptId": "c643f23f-80fc-5886-ad51-4145ac88b802"
  }
]
