=== hms-dbmi/ppm-data/picnichealth/drug.schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "array",
  "title": "The Root Schema",
  "items": {
    "$id": "#/items",
    "type": "object",
    "title": "The Items Schema",
    "required": [
      "drugId",
      "personId",
      "visitId",
      "conceptId",
      "startDate",
      "startDatePrecision",
      "endDate",
      "endDatePrecision",
      "strength",
      "doseFormConceptId",
      "doseValue",
      "doseUnitConceptId",
      "numberOfTimes",
      "intervalValue",
      "intervalUnitConceptId",
      "durationValue",
      "durationUnitConceptId",
      "timeOfDayConceptId",
      "asNeeded",
      "typeConceptId"
    ],
    "properties": {
      "drugId": {
        "$id": "#/items/properties/drugId",
        "type": "string",
        "title": "The Drugid Schema",
        "default": "",
        "examples": [
          "e26e8847-dcac-4341-8e4e-30d5aaacf85e"
        ],
        "pattern": "^(.*)$"
      },
      "personId": {
        "$id": "#/items/properties/personId",
        "type": "string",
        "title": "The Personid Schema",
        "default": "",
        "examples": [
          "81163710-c2a2-4750-8e7f-8c7e18575695"
        ],
        "pattern": "^(.*)$"
      },
      "visitId": {
        "$id": "#/items/properties/visitId",
        "type": "string",
        "title": "The Visitid Schema",
        "default": "",
        "examples": [
          "9f974f15-5df4-4c05-9779-f24f500f9cc5"
        ],
        "pattern": "^(.*)$"
      },
      "conceptId": {
        "$id": "#/items/properties/conceptId",
        "type": "string",
        "title": "The Conceptid Schema",
        "default": "",
        "examples": [
          "c67af3b5-cc6d-52d1-9434-221aca948d7b"
        ],
        "pattern": "^(.*)$"
      },
      "startDate": {
        "$id": "#/items/properties/startDate",
        "type": "string",
        "title": "The Startdate Schema",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      },
      "startDatePrecision": {
        "$id": "#/items/properties/startDatePrecision",
        "type": "string",
        "title": "The Startdateprecision Schema",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      },
      "endDate": {
        "$id": "#/items/properties/endDate",
        "type": "string",
        "title": "The Enddate Schema",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      },
      "endDatePrecision": {
        "$id": "#/items/properties/endDatePrecision",
        "type": "string",
        "title": "The Enddateprecision Schema",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      },
      "strength": {
        "$id": "#/items/properties/strength",
        "type": "string",
        "title": "The Strength Schema",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      },
      "doseFormConceptId": {
        "$id": "#/items/properties/doseFormConceptId",
        "type": "string",
        "title": "The Doseformconceptid Schema",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      },
      "doseValue": {
        "$id": "#/items/properties/doseValue",
        "type": "string",
        "title": "The Dosevalue Schema",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      },
      "doseUnitConceptId": {
        "$id": "#/items/properties/doseUnitConceptId",
        "type": "string",
        "title": "The Doseunitconceptid Schema",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      },
      "numberOfTimes": {
        "$id": "#/items/properties/numberOfTimes",
        "type": "string",
        "title": "The Numberoftimes Schema",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      },
      "intervalValue": {
        "$id": "#/items/properties/intervalValue",
        "type": "string",
        "title": "The Intervalvalue Schema",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      },
      "intervalUnitConceptId": {
        "$id": "#/items/properties/intervalUnitConceptId",
        "type": "string",
        "title": "The Intervalunitconceptid Schema",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      },
      "durationValue": {
        "$id": "#/items/properties/durationValue",
        "type": "string",
        "title": "The Durationvalue Schema",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      },
      "durationUnitConceptId": {
        "$id": "#/items/properties/durationUnitConceptId",
        "type": "string",
        "title": "The Durationunitconceptid Schema",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      },
      "timeOfDayConceptId": {
        "$id": "#/items/properties/timeOfDayConceptId",
        "type": "string",
        "title": "The Timeofdayconceptid Schema",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      },
      "asNeeded": {
        "$id": "#/items/properties/asNeeded",
        "type": "string",
        "title": "The Asneeded Schema",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      },
      "typeConceptId": {
        "$id": "#/items/properties/typeConceptId",
        "type": "string",
        "title": "The Typeconceptid Schema",
        "default": "",
        "examples": [
          "a1f9aa3d-7c59-53ea-8131-a77503a16c5e"
        ],
        "pattern": "^(.*)$"
      }
    }
  }
}

=== hms-dbmi/ppm-data/picnichealth/example/drug.json
[
  {
    "drugId": "e26e8847-dcac-4341-8e4e-30d5aaacf85e",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "visitId": "9f974f15-5df4-4c05-9779-f24f500f9cc5",
    "conceptId": "c67af3b5-cc6d-52d1-9434-221aca948d7b",
    "startDate": "",
    "startDatePrecision": "",
    "endDate": "",
    "endDatePrecision": "",
    "strength": "",
    "doseFormConceptId": "",
    "doseValue": "",
    "doseUnitConceptId": "",
    "numberOfTimes": "",
    "intervalValue": "",
    "intervalUnitConceptId": "",
    "durationValue": "",
    "durationUnitConceptId": "",
    "timeOfDayConceptId": "",
    "asNeeded": "",
    "typeConceptId": "a1f9aa3d-7c59-53ea-8131-a77503a16c5e"
  },
  {
    "drugId": "5c99a443-d885-4073-9128-ef7e586e48af",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "visitId": "6a21415e-fae5-49f6-bebb-ef8b3a7b4ed1",
    "conceptId": "c67af3b5-cc6d-52d1-9434-221aca948d7b",
    "startDate": "",
    "startDatePrecision": "",
    "endDate": "",
    "endDatePrecision": "",
    "strength": "",
    "doseFormConceptId": "",
    "doseValue": "",
    "doseUnitConceptId": "",
    "numberOfTimes": "",
    "intervalValue": "",
    "intervalUnitConceptId": "",
    "durationValue": "",
    "durationUnitConceptId": "",
    "timeOfDayConceptId": "",
    "asNeeded": "",
    "typeConceptId": "a1f9aa3d-7c59-53ea-8131-a77503a16c5e"
  },
  {
    "drugId": "7b48b185-0e56-4c83-bc20-d4fd7c946809",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "visitId": "6a21415e-fae5-49f6-bebb-ef8b3a7b4ed1",
    "conceptId": "64d53873-1b92-4bab-959b-b34fb362a4da",
    "startDate": "",
    "startDatePrecision": "",
    "endDate": "",
    "endDatePrecision": "",
    "strength": "",
    "doseFormConceptId": "",
    "doseValue": "",
    "doseUnitConceptId": "",
    "numberOfTimes": "",
    "intervalValue": "",
    "intervalUnitConceptId": "",
    "durationValue": "",
    "durationUnitConceptId": "",
    "timeOfDayConceptId": "",
    "asNeeded": "",
    "typeConceptId": "a1f9aa3d-7c59-53ea-8131-a77503a16c5e"
  },
  {
    "drugId": "38db062d-7f34-4c42-a5cd-bbe0223ba192",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "visitId": "6a21415e-fae5-49f6-bebb-ef8b3a7b4ed1",
    "conceptId": "f118231d-aa87-58a5-bc5f-f12c835a4597",
    "startDate": "",
    "startDatePrecision": "",
    "endDate": "",
    "endDatePrecision": "",
    "strength": "",
    "doseFormConceptId": "",
    "doseValue": "",
    "doseUnitConceptId": "",
    "numberOfTimes": "",
    "intervalValue": "",
    "intervalUnitConceptId": "",
    "durationValue": "",
    "durationUnitConceptId": "",
    "timeOfDayConceptId": "",
    "asNeeded": "",
    "typeConceptId": "a1f9aa3d-7c59-53ea-8131-a77503a16c5e"
  },
  {
    "drugId": "ce777f3b-a7df-4e50-9555-bfba8b95c8ee",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "visitId": "dc2a52bf-e100-45a1-abec-9f68a7f50888",
    "conceptId": "f58ab932-bc44-4548-a900-90cf9a7c988f",
    "startDate": "",
    "startDatePrecision": "",
    "endDate": "",
    "endDatePrecision": "",
    "strength": "",
    "doseFormConceptId": "",
    "doseValue": "",
    "doseUnitConceptId": "",
    "numberOfTimes": "",
    "intervalValue": "",
    "intervalUnitConceptId": "",
    "durationValue": "",
    "durationUnitConceptId": "",
    "timeOfDayConceptId": "",
    "asNeeded": "",
    "typeConceptId": "a1f9aa3d-7c59-53ea-8131-a77503a16c5e"
  },
  {
    "drugId": "f9af04e6-7b7c-4da7-8bf1-a0b89b7f9ff3",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "visitId": "dc2a52bf-e100-45a1-abec-9f68a7f50888",
    "conceptId": "8d88f28e-acd1-578c-ae3f-06b568b7b98b",
    "startDate": "",
    "startDatePrecision": "",
    "endDate": "",
    "endDatePrecision": "",
    "strength": "",
    "doseFormConceptId": "91e01f26-1793-5432-98cb-a2c7b50af232",
    "doseValue": "",
    "doseUnitConceptId": "",
    "numberOfTimes": "",
    "intervalValue": "",
    "intervalUnitConceptId": "",
    "durationValue": "",
    "durationUnitConceptId": "",
    "timeOfDayConceptId": "",
    "asNeeded": "",
    "typeConceptId": "a1f9aa3d-7c59-53ea-8131-a77503a16c5e"
  },
  {
    "drugId": "58c55a1b-4416-4daf-b54c-1d626196f966",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "visitId": "dc2a52bf-e100-45a1-abec-9f68a7f50888",
    "conceptId": "57ec1676-b31f-58b0-b9c7-0ea2c83c51f5",
    "startDate": "",
    "startDatePrecision": "",
    "endDate": "",
    "endDatePrecision": "",
    "strength": "",
    "doseFormConceptId": "91e01f26-1793-5432-98cb-a2c7b50af232",
    "doseValue": "",
    "doseUnitConceptId": "",
    "numberOfTimes": "",
    "intervalValue": "",
    "intervalUnitConceptId": "",
    "durationValue": "",
    "durationUnitConceptId": "",
    "timeOfDayConceptId": "",
    "asNeeded": false,
    "typeConceptId": "a1f9aa3d-7c59-53ea-8131-a77503a16c5e"
  },
  {
    "drugId": "d78ffed8-2450-4a44-886b-afe6022c8101",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "visitId": "8b13585f-ca45-4570-bacd-165efe36546a",
    "conceptId": "35c0e7de-84d8-4f23-adc4-018246a6d923",
    "startDate": "",
    "startDatePrecision": "",
    "endDate": "",
    "endDatePrecision": "",
    "strength": "",
    "doseFormConceptId": "",
    "doseValue": "",
    "doseUnitConceptId": "",
    "numberOfTimes": "",
    "intervalValue": 1,
    "intervalUnitConceptId": "f07bffb9-6d3b-512a-b490-276b37a9e099",
    "durationValue": "",
    "durationUnitConceptId": "",
    "timeOfDayConceptId": "",
    "asNeeded": false,
    "typeConceptId": "a1f9aa3d-7c59-53ea-8131-a77503a16c5e"
  },
  {
    "drugId": "4caee145-ed32-4cc0-9eed-ec252ce38606",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "visitId": "8b13585f-ca45-4570-bacd-165efe36546a",
    "conceptId": "c125a142-c6da-4f51-8a8d-0477afb79c81",
    "startDate": "",
    "startDatePrecision": "",
    "endDate": "",
    "endDatePrecision": "",
    "strength": "",
    "doseFormConceptId": "91e01f26-1793-5432-98cb-a2c7b50af232",
    "doseValue": "",
    "doseUnitConceptId": "",
    "numberOfTimes": "",
    "intervalValue": "",
    "intervalUnitConceptId": "",
    "durationValue": "",
    "durationUnitConceptId": "",
    "timeOfDayConceptId": "",
    "asNeeded": false,
    "typeConceptId": "a1f9aa3d-7c59-53ea-8131-a77503a16c5e"
  },
  {
    "drugId": "ec0ef937-efbe-4860-bf77-2d67154d83e0",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "visitId": "ca1affe7-b192-4128-85ef-8599a0d572d4",
    "conceptId": "c125a142-c6da-4f51-8a8d-0477afb79c81",
    "startDate": "",
    "startDatePrecision": "",
    "endDate": "",
    "endDatePrecision": "",
    "strength": "",
    "doseFormConceptId": "91e01f26-1793-5432-98cb-a2c7b50af232",
    "doseValue": "",
    "doseUnitConceptId": "",
    "numberOfTimes": "",
    "intervalValue": 1,
    "intervalUnitConceptId": "76bc333a-dc86-5a05-a0da-5840e06db28f",
    "durationValue": "",
    "durationUnitConceptId": "",
    "timeOfDayConceptId": "",
    "asNeeded": false,
    "typeConceptId": "a1f9aa3d-7c59-53ea-8131-a77503a16c5e"
  },
  {
    "drugId": "241dc308-537b-4d9a-8904-d381f6a1958e",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "visitId": "9b9a01c1-381c-4b0b-851a-26089357ab34",
    "conceptId": "c125a142-c6da-4f51-8a8d-0477afb79c81",
    "startDate": "",
    "startDatePrecision": "",
    "endDate": "",
    "endDatePrecision": "",
    "strength": "",
    "doseFormConceptId": "91e01f26-1793-5432-98cb-a2c7b50af232",
    "doseValue": "",
    "doseUnitConceptId": "",
    "numberOfTimes": "",
    "intervalValue": 1,
    "intervalUnitConceptId": "76bc333a-dc86-5a05-a0da-5840e06db28f",
    "durationValue": "",
    "durationUnitConceptId": "",
    "timeOfDayConceptId": "",
    "asNeeded": false,
    "typeConceptId": "a1f9aa3d-7c59-53ea-8131-a77503a16c5e"
  },
  {
    "drugId": "34126f64-2882-41e0-b2d8-5d2a7c70746f",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "visitId": "7f595fa9-f124-4371-8fb8-9fdd9bab0ac1",
    "conceptId": "35c0e7de-84d8-4f23-adc4-018246a6d923",
    "startDate": "",
    "startDatePrecision": "",
    "endDate": "",
    "endDatePrecision": "",
    "strength": "",
    "doseFormConceptId": "",
    "doseValue": "",
    "doseUnitConceptId": "",
    "numberOfTimes": "",
    "intervalValue": "",
    "intervalUnitConceptId": "",
    "durationValue": "",
    "durationUnitConceptId": "",
    "timeOfDayConceptId": "",
    "asNeeded": "",
    "typeConceptId": "a1f9aa3d-7c59-53ea-8131-a77503a16c5e"
  },
  {
    "drugId": "e801c974-469d-4dd6-8746-1610e5781449",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "visitId": "7f595fa9-f124-4371-8fb8-9fdd9bab0ac1",
    "conceptId": "745c3af1-fcfd-5009-a09e-622e110fe7b3",
    "startDate": "",
    "startDatePrecision": "",
    "endDate": "",
    "endDatePrecision": "",
    "strength": "",
    "doseFormConceptId": "",
    "doseValue": "",
    "doseUnitConceptId": "",
    "numberOfTimes": "",
    "intervalValue": "",
    "intervalUnitConceptId": "",
    "durationValue": "",
    "durationUnitConceptId": "",
    "timeOfDayConceptId": "",
    "asNeeded": "",
    "typeConceptId": "a1f9aa3d-7c59-53ea-8131-a77503a16c5e"
  },
  {
    "drugId": "d7439b79-eaa8-4f8f-9f7d-87c20b9ebd5e",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "visitId": "7f595fa9-f124-4371-8fb8-9fdd9bab0ac1",
    "conceptId": "179ad5f6-93f2-4487-b711-53be1244437a",
    "startDate": "",
    "startDatePrecision": "",
    "endDate": "",
    "endDatePrecision": "",
    "strength": "",
    "doseFormConceptId": "",
    "doseValue": "",
    "doseUnitConceptId": "",
    "numberOfTimes": "",
    "intervalValue": "",
    "intervalUnitConceptId": "",
    "durationValue": "",
    "durationUnitConceptId": "",
    "timeOfDayConceptId": "",
    "asNeeded": "",
    "typeConceptId": "a1f9aa3d-7c59-53ea-8131-a77503a16c5e"
  },
  {
    "drugId": "2571b045-642d-488f-af45-433531019eff",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "visitId": "7f595fa9-f124-4371-8fb8-9fdd9bab0ac1",
