=== hms-dbmi/ppm-data/picnichealth/drugReadable.schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "array",
  "title": "The Root Schema",
  "items": {
    "$id": "#/items",
    "type": "object",
    "title": "The Items Schema",
    "required": [
      "drugId",
      "personId",
      "visitId",
      "conceptName",
      "startDate",
      "startDatePrecision",
      "endDate",
      "endDatePrecision",
      "strength",
      "doseFormConceptName",
      "doseValue",
      "doseUnitConceptName",
      "numberOfTimes",
      "intervalValue",
      "intervalUnitConceptName",
      "durationValue",
      "durationUnitConceptName",
      "timeOfDayConceptName",
      "asNeeded",
      "typeConceptName"
    ],
    "properties": {
      "drugId": {
        "$id": "#/items/properties/drugId",
        "type": "string",
        "title": "The Drugid Schema",
        "default": "",
        "examples": [
          "e26e8847-dcac-4341-8e4e-30d5aaacf85e"
        ],
        "pattern": "^(.*)$"
      },
      "personId": {
        "$id": "#/items/properties/personId",
        "type": "string",
        "title": "The Personid Schema",
        "default": "",
        "examples": [
          "81163710-c2a2-4750-8e7f-8c7e18575695"
        ],
        "pattern": "^(.*)$"
      },
      "visitId": {
        "$id": "#/items/properties/visitId",
        "type": "string",
        "title": "The Visitid Schema",
        "default": "",
        "examples": [
          "9f974f15-5df4-4c05-9779-f24f500f9cc5"
        ],
        "pattern": "^(.*)$"
      },
      "conceptName": {
        "$id": "#/items/properties/conceptName",
        "type": "string",
        "title": "The Conceptname Schema",
        "default": "",
        "examples": [
          "Fish Oils"
        ],
        "pattern": "^(.*)$"
      },
      "startDate": {
        "$id": "#/items/properties/startDate",
        "type": "string",
        "title": "The Startdate Schema",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      },
      "startDatePrecision": {
        "$id": "#/items/properties/startDatePrecision",
        "type": "string",
        "title": "The Startdateprecision Schema",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      },
      "endDate": {
        "$id": "#/items/properties/endDate",
        "type": "string",
        "title": "The Enddate Schema",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      },
      "endDatePrecision": {
        "$id": "#/items/properties/endDatePrecision",
        "type": "string",
        "title": "The Enddateprecision Schema",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      },
      "strength": {
        "$id": "#/items/properties/strength",
        "type": "string",
        "title": "The Strength Schema",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      },
      "doseFormConceptName": {
        "$id": "#/items/properties/doseFormConceptName",
        "type": "string",
        "title": "The Doseformconceptname Schema",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      },
      "doseValue": {
        "$id": "#/items/properties/doseValue",
        "type": "string",
        "title": "The Dosevalue Schema",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      },
      "doseUnitConceptName": {
        "$id": "#/items/properties/doseUnitConceptName",
        "type": "string",
        "title": "The Doseunitconceptname Schema",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      },
      "numberOfTimes": {
        "$id": "#/items/properties/numberOfTimes",
        "type": "string",
        "title": "The Numberoftimes Schema",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      },
      "intervalValue": {
        "$id": "#/items/properties/intervalValue",
        "type": "string",
        "title": "The Intervalvalue Schema",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      },
      "intervalUnitConceptName": {
        "$id": "#/items/properties/intervalUnitConceptName",
        "type": "string",
        "title": "The Intervalunitconceptname Schema",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      },
      "durationValue": {
        "$id": "#/items/properties/durationValue",
        "type": "string",
        "title": "The Durationvalue Schema",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      },
      "durationUnitConceptName": {
        "$id": "#/items/properties/durationUnitConceptName",
        "type": "string",
        "title": "The Durationunitconceptname Schema",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      },
      "timeOfDayConceptName": {
        "$id": "#/items/properties/timeOfDayConceptName",
        "type": "string",
        "title": "The Timeofdayconceptname Schema",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      },
      "asNeeded": {
        "$id": "#/items/properties/asNeeded",
        "type": "string",
        "title": "The Asneeded Schema",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      },
      "typeConceptName": {
        "$id": "#/items/properties/typeConceptName",
        "type": "string",
        "title": "The Typeconceptname Schema",
        "default": "",
        "examples": [
          "Medication list entry"
        ],
        "pattern": "^(.*)$"
      }
    }
  }
}

=== hms-dbmi/ppm-data/picnichealth/example/drugReadable.json
[
  {
    "drugId": "e26e8847-dcac-4341-8e4e-30d5aaacf85e",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "visitId": "9f974f15-5df4-4c05-9779-f24f500f9cc5",
    "conceptName": "Fish Oils",
    "startDate": "",
    "startDatePrecision": "",
    "endDate": "",
    "endDatePrecision": "",
    "strength": "",
    "doseFormConceptName": "",
    "doseValue": "",
    "doseUnitConceptName": "",
    "numberOfTimes": "",
    "intervalValue": "",
    "intervalUnitConceptName": "",
    "durationValue": "",
    "durationUnitConceptName": "",
    "timeOfDayConceptName": "",
    "asNeeded": "",
    "typeConceptName": "Medication list entry"
  },
  {
    "drugId": "5c99a443-d885-4073-9128-ef7e586e48af",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "visitId": "6a21415e-fae5-49f6-bebb-ef8b3a7b4ed1",
    "conceptName": "Fish Oils",
    "startDate": "",
    "startDatePrecision": "",
    "endDate": "",
    "endDatePrecision": "",
    "strength": "",
    "doseFormConceptName": "",
    "doseValue": "",
    "doseUnitConceptName": "",
    "numberOfTimes": "",
    "intervalValue": "",
    "intervalUnitConceptName": "",
    "durationValue": "",
    "durationUnitConceptName": "",
    "timeOfDayConceptName": "",
    "asNeeded": "",
    "typeConceptName": "Medication list entry"
  },
  {
    "drugId": "7b48b185-0e56-4c83-bc20-d4fd7c946809",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "visitId": "6a21415e-fae5-49f6-bebb-ef8b3a7b4ed1",
    "conceptName": "Peptazole",
    "startDate": "",
    "startDatePrecision": "",
    "endDate": "",
    "endDatePrecision": "",
    "strength": "",
    "doseFormConceptName": "",
    "doseValue": "",
    "doseUnitConceptName": "",
    "numberOfTimes": "",
    "intervalValue": "",
    "intervalUnitConceptName": "",
    "durationValue": "",
    "durationUnitConceptName": "",
    "timeOfDayConceptName": "",
    "asNeeded": "",
    "typeConceptName": "Medication list entry"
  },
  {
    "drugId": "38db062d-7f34-4c42-a5cd-bbe0223ba192",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "visitId": "6a21415e-fae5-49f6-bebb-ef8b3a7b4ed1",
    "conceptName": "Multivitamin preparation",
    "startDate": "",
    "startDatePrecision": "",
    "endDate": "",
    "endDatePrecision": "",
    "strength": "",
    "doseFormConceptName": "",
    "doseValue": "",
    "doseUnitConceptName": "",
    "numberOfTimes": "",
    "intervalValue": "",
    "intervalUnitConceptName": "",
    "durationValue": "",
    "durationUnitConceptName": "",
    "timeOfDayConceptName": "",
    "asNeeded": "",
    "typeConceptName": "Medication list entry"
  },
  {
    "drugId": "ce777f3b-a7df-4e50-9555-bfba8b95c8ee",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "visitId": "dc2a52bf-e100-45a1-abec-9f68a7f50888",
    "conceptName": "Xeroform",
    "startDate": "",
    "startDatePrecision": "",
    "endDate": "",
    "endDatePrecision": "",
    "strength": "",
    "doseFormConceptName": "",
    "doseValue": "",
    "doseUnitConceptName": "",
    "numberOfTimes": "",
    "intervalValue": "",
    "intervalUnitConceptName": "",
    "durationValue": "",
    "durationUnitConceptName": "",
    "timeOfDayConceptName": "",
    "asNeeded": "",
    "typeConceptName": "Medication list entry"
  },
  {
    "drugId": "f9af04e6-7b7c-4da7-8bf1-a0b89b7f9ff3",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "visitId": "dc2a52bf-e100-45a1-abec-9f68a7f50888",
    "conceptName": "Cefazolin Injectable Product",
    "startDate": "",
    "startDatePrecision": "",
    "endDate": "",
    "endDatePrecision": "",
    "strength": "",
    "doseFormConceptName": "Injectable Product",
    "doseValue": "",
    "doseUnitConceptName": "",
    "numberOfTimes": "",
    "intervalValue": "",
    "intervalUnitConceptName": "",
    "durationValue": "",
    "durationUnitConceptName": "",
    "timeOfDayConceptName": "",
    "asNeeded": "",
    "typeConceptName": "Medication list entry"
  },
  {
    "drugId": "58c55a1b-4416-4daf-b54c-1d626196f966",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "visitId": "dc2a52bf-e100-45a1-abec-9f68a7f50888",
    "conceptName": "Epinephrine / Lidocaine Injectable Product",
    "startDate": "",
    "startDatePrecision": "",
    "endDate": "",
    "endDatePrecision": "",
    "strength": "",
    "doseFormConceptName": "Injectable Product",
    "doseValue": "",
    "doseUnitConceptName": "",
    "numberOfTimes": "",
    "intervalValue": "",
    "intervalUnitConceptName": "",
    "durationValue": "",
    "durationUnitConceptName": "",
    "timeOfDayConceptName": "",
    "asNeeded": false,
    "typeConceptName": "Medication list entry"
  },
  {
    "drugId": "d78ffed8-2450-4a44-886b-afe6022c8101",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "visitId": "8b13585f-ca45-4570-bacd-165efe36546a",
    "conceptName": "ASEA",
    "startDate": "",
    "startDatePrecision": "",
    "endDate": "",
    "endDatePrecision": "",
    "strength": "",
    "doseFormConceptName": "",
    "doseValue": "",
    "doseUnitConceptName": "",
    "numberOfTimes": "",
    "intervalValue": 1,
    "intervalUnitConceptName": "day",
    "durationValue": "",
    "durationUnitConceptName": "",
    "timeOfDayConceptName": "",
    "asNeeded": false,
    "typeConceptName": "Medication list entry"
  },
  {
    "drugId": "4caee145-ed32-4cc0-9eed-ec252ce38606",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "visitId": "8b13585f-ca45-4570-bacd-165efe36546a",
    "conceptName": "Coley's toxins Injectable Product",
    "startDate": "",
    "startDatePrecision": "",
    "endDate": "",
    "endDatePrecision": "",
    "strength": "",
    "doseFormConceptName": "Injectable Product",
    "doseValue": "",
    "doseUnitConceptName": "",
    "numberOfTimes": "",
    "intervalValue": "",
    "intervalUnitConceptName": "",
    "durationValue": "",
    "durationUnitConceptName": "",
    "timeOfDayConceptName": "",
    "asNeeded": false,
    "typeConceptName": "Medication list entry"
  },
  {
    "drugId": "ec0ef937-efbe-4860-bf77-2d67154d83e0",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "visitId": "ca1affe7-b192-4128-85ef-8599a0d572d4",
    "conceptName": "Coley's toxins Injectable Product",
    "startDate": "",
    "startDatePrecision": "",
    "endDate": "",
    "endDatePrecision": "",
    "strength": "",
    "doseFormConceptName": "Injectable Product",
    "doseValue": "",
    "doseUnitConceptName": "",
    "numberOfTimes": "",
    "intervalValue": 1,
    "intervalUnitConceptName": "week",
    "durationValue": "",
    "durationUnitConceptName": "",
    "timeOfDayConceptName": "",
    "asNeeded": false,
    "typeConceptName": "Medication list entry"
  },
  {
    "drugId": "241dc308-537b-4d9a-8904-d381f6a1958e",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "visitId": "9b9a01c1-381c-4b0b-851a-26089357ab34",
    "conceptName": "Coley's toxins Injectable Product",
    "startDate": "",
    "startDatePrecision": "",
    "endDate": "",
    "endDatePrecision": "",
    "strength": "",
    "doseFormConceptName": "Injectable Product",
    "doseValue": "",
    "doseUnitConceptName": "",
    "numberOfTimes": "",
    "intervalValue": 1,
    "intervalUnitConceptName": "week",
    "durationValue": "",
    "durationUnitConceptName": "",
    "timeOfDayConceptName": "",
    "asNeeded": false,
    "typeConceptName": "Medication list entry"
  },
  {
    "drugId": "34126f64-2882-41e0-b2d8-5d2a7c70746f",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "visitId": "7f595fa9-f124-4371-8fb8-9fdd9bab0ac1",
    "conceptName": "ASEA",
    "startDate": "",
    "startDatePrecision": "",
    "endDate": "",
    "endDatePrecision": "",
    "strength": "",
    "doseFormConceptName": "",
    "doseValue": "",
    "doseUnitConceptName": "",
    "numberOfTimes": "",
    "intervalValue": "",
    "intervalUnitConceptName": "",
    "durationValue": "",
    "durationUnitConceptName": "",
    "timeOfDayConceptName": "",
    "asNeeded": "",
    "typeConceptName": "Medication list entry"
  },
  {
    "drugId": "e801c974-469d-4dd6-8746-1610e5781449",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "visitId": "7f595fa9-f124-4371-8fb8-9fdd9bab0ac1",
    "conceptName": "Vitamin E",
    "startDate": "",
    "startDatePrecision": "",
    "endDate": "",
    "endDatePrecision": "",
    "strength": "",
    "doseFormConceptName": "",
    "doseValue": "",
    "doseUnitConceptName": "",
    "numberOfTimes": "",
    "intervalValue": "",
    "intervalUnitConceptName": "",
    "durationValue": "",
    "durationUnitConceptName": "",
    "timeOfDayConceptName": "",
    "asNeeded": "",
    "typeConceptName": "Medication list entry"
  },
  {
    "drugId": "d7439b79-eaa8-4f8f-9f7d-87c20b9ebd5e",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "visitId": "7f595fa9-f124-4371-8fb8-9fdd9bab0ac1",
    "conceptName": "para-aminobenzoic acid",
    "startDate": "",
    "startDatePrecision": "",
    "endDate": "",
    "endDatePrecision": "",
    "strength": "",
    "doseFormConceptName": "",
    "doseValue": "",
    "doseUnitConceptName": "",
    "numberOfTimes": "",
    "intervalValue": "",
    "intervalUnitConceptName": "",
    "durationValue": "",
    "durationUnitConceptName": "",
    "timeOfDayConceptName": "",
    "asNeeded": "",
    "typeConceptName": "Medication list entry"
  },
  {
    "drugId": "2571b045-642d-488f-af45-433531019eff",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "visitId": "7f595fa9-f124-4371-8fb8-9fdd9bab0ac1",
    "conceptName": "Korean ginseng preparation",
    "startDate": "",
    "startDatePrecision": "",
    "endDate": "",
    "endDatePrecision": "",
    "strength": "",
    "doseFormConceptName": "",
    "doseValue": "",
    "doseUnitConceptName": "",
    "numberOfTimes": "",
    "intervalValue": "",
    "intervalUnitConceptName": "",
    "durationValue": "",
    "durationUnitConceptName": "",
    "timeOfDayConceptName": "",
    "asNeeded": "",
