=== hms-dbmi/ppm-data/picnichealth/visit.schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "array",
  "title": "The Root Schema",
  "items": {
    "$id": "#/items",
    "type": "object",
    "title": "The Items Schema",
    "required": [
      "visitId",
      "personId",
      "conceptId",
      "startDate",
      "startDatePrecision",
      "endDate",
      "endDatePrecision",
      "title",
      "subtitle",
      "careSiteId",
      "performingProviderId",
      "referringProviderId"
    ],
    "properties": {
      "visitId": {
        "$id": "#/items/properties/visitId",
        "type": "string",
        "title": "The Visitid Schema",
        "default": "",
        "examples": [
          "dc2a52bf-e100-45a1-abec-9f68a7f50888"
        ],
        "pattern": "^(.*)$"
      },
      "personId": {
        "$id": "#/items/properties/personId",
        "type": "string",
        "title": "The Personid Schema",
        "default": "",
        "examples": [
          "81163710-c2a2-4750-8e7f-8c7e18575695"
        ],
        "pattern": "^(.*)$"
      },
      "conceptId": {
        "$id": "#/items/properties/conceptId",
        "type": "string",
        "title": "The Conceptid Schema",
        "default": "",
        "examples": [
          "37d63769-cfc5-563e-87cd-49f0e3c5b034"
        ],
        "pattern": "^(.*)$"
      },
      "startDate": {
        "$id": "#/items/properties/startDate",
        "type": "string",
        "title": "The Startdate Schema",
        "default": "",
        "examples": [
          "2008-02-26T12:00:00"
        ],
        "pattern": "^(.*)$"
      },
      "startDatePrecision": {
        "$id": "#/items/properties/startDatePrecision",
        "type": "string",
        "title": "The Startdateprecision Schema",
        "default": "",
        "examples": [
          "DAY"
        ],
        "pattern": "^(.*)$"
      },
      "endDate": {
        "$id": "#/items/properties/endDate",
        "type": "string",
        "title": "The Enddate Schema",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      },
      "endDatePrecision": {
        "$id": "#/items/properties/endDatePrecision",
        "type": "string",
        "title": "The Enddateprecision Schema",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      },
      "title": {
        "$id": "#/items/properties/title",
        "type": "string",
        "title": "The Title Schema",
        "default": "",
        "examples": [
          "Right Comprehensive Neck Dissection"
        ],
        "pattern": "^(.*)$"
      },
      "subtitle": {
        "$id": "#/items/properties/subtitle",
        "type": "string",
        "title": "The Subtitle Schema",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      },
      "careSiteId": {
        "$id": "#/items/properties/careSiteId",
        "type": "string",
        "title": "The Caresiteid Schema",
        "default": "",
        "examples": [
          "3fa3ceab-4085-4033-86c6-c31f075df0d8"
        ],
        "pattern": "^(.*)$"
      },
      "performingProviderId": {
        "$id": "#/items/properties/performingProviderId",
        "type": "string",
        "title": "The Performingproviderid Schema",
        "default": "",
        "examples": [
          "c39b2081-23ae-489f-b1aa-9168926ae522"
        ],
        "pattern": "^(.*)$"
      },
      "referringProviderId": {
        "$id": "#/items/properties/referringProviderId",
        "type": "string",
        "title": "The Referringproviderid Schema",
        "default": "",
        "examples": [
          ""
        ],
        "pattern": "^(.*)$"
      }
    }
  }
}

=== hms-dbmi/ppm-data/picnichealth/example/visit.json
[
  {
    "visitId": "dc2a52bf-e100-45a1-abec-9f68a7f50888",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "conceptId": "37d63769-cfc5-563e-87cd-49f0e3c5b034",
    "startDate": "2008-02-26T12:00:00",
    "startDatePrecision": "DAY",
    "endDate": "",
    "endDatePrecision": "",
    "title": "Right Comprehensive Neck Dissection",
    "subtitle": "",
    "careSiteId": "3fa3ceab-4085-4033-86c6-c31f075df0d8",
    "performingProviderId": "c39b2081-23ae-489f-b1aa-9168926ae522",
    "referringProviderId": ""
  },
  {
    "visitId": "97be658c-6395-401f-8b7d-eb3ec82cbcf0",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "conceptId": "f827c1a1-8b79-5452-b51a-0ca2014591a3",
    "startDate": "2010-06-16T12:00:00",
    "startDatePrecision": "DAY",
    "endDate": "",
    "endDatePrecision": "",
    "title": "PET/CT",
    "subtitle": "Whole Body",
    "careSiteId": "0833e399-8682-4d3f-94ee-57f5cd179e66",
    "performingProviderId": "580588c8-3e4b-4dac-8ba1-03b7c6194484",
    "referringProviderId": ""
  },
  {
    "visitId": "67ca7a5f-4a62-492e-ae9a-f15b68868441",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "conceptId": "b6c432ab-0d26-59cf-9dd4-840098bde6c0",
    "startDate": "2008-02-27T12:00:00",
    "startDatePrecision": "DAY",
    "endDate": "",
    "endDatePrecision": "",
    "title": "Pathology",
    "subtitle": "Neck/Parotid gland",
    "careSiteId": "3fa3ceab-4085-4033-86c6-c31f075df0d8",
    "performingProviderId": "3ec3f939-c40a-4506-91ec-1b2be47a4690",
    "referringProviderId": ""
  },
  {
    "visitId": "b11747a4-6552-4bc9-826a-498415e3d161",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "conceptId": "b6c432ab-0d26-59cf-9dd4-840098bde6c0",
    "startDate": "2010-10-29T12:00:00",
    "startDatePrecision": "DAY",
    "endDate": "",
    "endDatePrecision": "",
    "title": "Pathology",
    "subtitle": "Lymph Nodes",
    "careSiteId": "0833e399-8682-4d3f-94ee-57f5cd179e66",
    "performingProviderId": "f4a23aba-a5e9-438e-9b50-8ef9a1643438",
    "referringProviderId": ""
  },
  {
    "visitId": "2236186a-a2d7-4bac-8b8a-e98015c94089",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "conceptId": "041b3c2a-0392-5274-a51a-6e66fcfa06d3",
    "startDate": "2010-11-23T12:00:00",
    "startDatePrecision": "DAY",
    "endDate": "",
    "endDatePrecision": "",
    "title": "Office Visit",
    "subtitle": "Hematology/Oncology",
    "careSiteId": "3fa3ceab-4085-4033-86c6-c31f075df0d8",
    "performingProviderId": "d12e9433-d227-4b3b-ad27-fff34f2a4b92",
    "referringProviderId": ""
  },
  {
    "visitId": "328f890e-1e9e-4da7-9f84-3e0de345a71b",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "conceptId": "37d63769-cfc5-563e-87cd-49f0e3c5b034",
    "startDate": "2011-01-19T12:00:00",
    "startDatePrecision": "DAY",
    "endDate": "",
    "endDatePrecision": "",
    "title": "Right Ear Partial Resection",
    "subtitle": "",
    "careSiteId": "91537317-28f6-4d7a-aafb-482ec46238cf",
    "performingProviderId": "0846e325-8c2d-4765-9038-db6315aa3792",
    "referringProviderId": ""
  },
  {
    "visitId": "1f886ee7-4f98-4d48-ae74-6d7be1a79126",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "conceptId": "cef1500e-1cd8-59e2-9a84-f59e9faeda64",
    "startDate": "2010-11-23T12:00:00",
    "startDatePrecision": "DAY",
    "endDate": "",
    "endDatePrecision": "",
    "title": "Labs",
    "subtitle": "",
    "careSiteId": "41b8dea5-dd9f-405c-8ace-fdb0d111ef80",
    "performingProviderId": "",
    "referringProviderId": ""
  },
  {
    "visitId": "9dd3d353-ae7d-4008-975c-c0bab77c36fe",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "conceptId": "b6c432ab-0d26-59cf-9dd4-840098bde6c0",
    "startDate": "2007-12-07T12:00:00",
    "startDatePrecision": "DAY",
    "endDate": "",
    "endDatePrecision": "",
    "title": "Pathology",
    "subtitle": "Right Temple",
    "careSiteId": "72f01e3a-f6f5-4a87-9401-008cff8dd7b7",
    "performingProviderId": "ccdf3066-581f-46c2-bb40-5e88f27f6d9d",
    "referringProviderId": ""
  },
  {
    "visitId": "686265d3-2f06-49ed-9eeb-6c49e99b14f1",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "conceptId": "10fd74e6-dd4a-53f4-9199-bf224d8e3e92",
    "startDate": "2010-11-22T12:00:00",
    "startDatePrecision": "DAY",
    "endDate": "",
    "endDatePrecision": "",
    "title": "Kit Gene Mutation",
    "subtitle": "",
    "careSiteId": "2f70a4e6-55c1-4f99-a6db-bc8c56c31a10",
    "performingProviderId": "",
    "referringProviderId": ""
  },
  {
    "visitId": "a89c2ea5-cc10-41ad-888c-3cee093a2798",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "conceptId": "10fd74e6-dd4a-53f4-9199-bf224d8e3e92",
    "startDate": "2010-11-08T12:00:00",
    "startDatePrecision": "DAY",
    "endDate": "",
    "endDatePrecision": "",
    "title": "BRAF V600E Mutation",
    "subtitle": "",
    "careSiteId": "30073a85-9709-4896-bd2b-8d666896f19a",
    "performingProviderId": "",
    "referringProviderId": ""
  },
  {
    "visitId": "e687ced8-bbfe-43b1-bd93-572f642dfd22",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "conceptId": "b6c432ab-0d26-59cf-9dd4-840098bde6c0",
    "startDate": "2011-01-19T12:00:00",
    "startDatePrecision": "DAY",
    "endDate": "",
    "endDatePrecision": "",
    "title": "Pathology",
    "subtitle": "Chin Nodule",
    "careSiteId": "2917e62a-786b-4c94-a35c-f3869a4b3bff",
    "performingProviderId": "d5d3f007-69a2-46ce-a6f8-080689a97b5f",
    "referringProviderId": ""
  },
  {
    "visitId": "610a0e62-f1d3-4529-819b-2f6308212331",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "conceptId": "37d63769-cfc5-563e-87cd-49f0e3c5b034",
    "startDate": "2011-01-28T12:00:00",
    "startDatePrecision": "DAY",
    "endDate": "",
    "endDatePrecision": "",
    "title": "Radiation Therapy",
    "subtitle": "",
    "careSiteId": "31fc6341-f9b4-483d-956c-2de1b34a858f",
    "performingProviderId": "0bf29c3a-28bc-437d-ae25-ca99012062bc",
    "referringProviderId": ""
  },
  {
    "visitId": "7f595fa9-f124-4371-8fb8-9fdd9bab0ac1",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "conceptId": "041b3c2a-0392-5274-a51a-6e66fcfa06d3",
    "startDate": "2012-05-02T12:00:00",
    "startDatePrecision": "DAY",
    "endDate": "",
    "endDatePrecision": "",
    "title": "Office Visit",
    "subtitle": "Dermatology",
    "careSiteId": "4859415b-8a15-4d5b-9272-46ba5fe6886e",
    "performingProviderId": "beb293c4-94d2-443a-ada9-97be26967f76",
    "referringProviderId": ""
  },
  {
    "visitId": "8b13585f-ca45-4570-bacd-165efe36546a",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "conceptId": "041b3c2a-0392-5274-a51a-6e66fcfa06d3",
    "startDate": "2014-02-10T12:00:00",
    "startDatePrecision": "DAY",
    "endDate": "",
    "endDatePrecision": "",
    "title": "Office Visit",
    "subtitle": "Hematology/Oncology",
    "careSiteId": "4859415b-8a15-4d5b-9272-46ba5fe6886e",
    "performingProviderId": "26322bec-d2ab-45ed-84c7-c1cd86b90b9c",
    "referringProviderId": ""
  },
  {
    "visitId": "5dae0b24-b0af-46cc-91fb-e10784da03ef",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "conceptId": "f827c1a1-8b79-5452-b51a-0ca2014591a3",
    "startDate": "2011-12-14T12:00:00",
    "startDatePrecision": "DAY",
    "endDate": "",
    "endDatePrecision": "",
    "title": "NM/PET/CT",
    "subtitle": "Whole Body",
    "careSiteId": "c3c32175-dd7a-477a-a69b-93bacf364eb1",
    "performingProviderId": "d71ca47d-ad88-4abb-b86d-62963d1d31ef",
    "referringProviderId": ""
  },
  {
    "visitId": "9c9263e1-fb53-43fd-a41c-1bb6c5f732c0",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "conceptId": "f827c1a1-8b79-5452-b51a-0ca2014591a3",
    "startDate": "2010-08-16T12:00:00",
    "startDatePrecision": "DAY",
    "endDate": "",
    "endDatePrecision": "",
    "title": "PET/CT",
    "subtitle": "Whole Body",
    "careSiteId": "0833e399-8682-4d3f-94ee-57f5cd179e66",
    "performingProviderId": "580588c8-3e4b-4dac-8ba1-03b7c6194484",
    "referringProviderId": ""
  },
  {
    "visitId": "47ce8aaf-7069-4a6d-b5de-2fe8b74171f7",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "conceptId": "cef1500e-1cd8-59e2-9a84-f59e9faeda64",
    "startDate": "2011-12-14T12:00:00",
    "startDatePrecision": "DAY",
    "endDate": "",
    "endDatePrecision": "",
    "title": "Labs",
    "subtitle": "",
    "careSiteId": "c3c32175-dd7a-477a-a69b-93bacf364eb1",
    "performingProviderId": "",
    "referringProviderId": ""
  },
  {
    "visitId": "26b44c21-8f54-4907-b35e-5f59d3c35fe5",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "conceptId": "cef1500e-1cd8-59e2-9a84-f59e9faeda64",
    "startDate": "2010-08-16T12:00:00",
    "startDatePrecision": "DAY",
    "endDate": "",
    "endDatePrecision": "",
    "title": "Labs",
    "subtitle": "",
    "careSiteId": "c3c32175-dd7a-477a-a69b-93bacf364eb1",
    "performingProviderId": "",
    "referringProviderId": ""
  },
  {
    "visitId": "feea7080-2161-479d-a8b4-59d89b89d14a",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "conceptId": "041b3c2a-0392-5274-a51a-6e66fcfa06d3",
    "startDate": "2010-03-17T12:00:00",
    "startDatePrecision": "DAY",
    "endDate": "",
    "endDatePrecision": "",
    "title": "Office Visit",
    "subtitle": "Hematology/Oncology",
    "careSiteId": "c3c32175-dd7a-477a-a69b-93bacf364eb1",
    "performingProviderId": "beb293c4-94d2-443a-ada9-97be26967f76",
    "referringProviderId": ""
  },
  {
    "visitId": "77840519-0fb3-471e-adc9-6f7ead0e22d8",
    "personId": "81163710-c2a2-4750-8e7f-8c7e18575695",
    "conceptId": "041b3c2a-0392-5274-a51a-6e66fcfa06d3",
    "startDate": "2010-04-14T12:00:00",
    "startDatePrecision": "DAY",
    "endDate": "",
    "endDatePrecision": "",
    "title": "Office Visit",
    "subtitle": "Hematology/Oncology",
    "careSiteId": "c3c32175-dd7a-477a-a69b-93bacf364eb1",
    "performingProviderId": "49fdf711-33a4-41f6-82cb-46c1d47e8544",
